import { Fragment, useEffect, useMemo, useState } from 'react';
import { toast } from 'react-toastify';
import { getAllBrowserHistory, getTagsForHistory } from '../api/browserHistoryApi';
import { getAllTags } from '../api/tagApi';
import { addManualTag, removeTagLink } from '../api/browserHistoryTagApi';
import { formatDateTime } from '../utils/format';
import TablePagination from '../components/TablePagination';

export default function BrowserHistoryPage() {
  const [history, setHistory] = useState([]); const [allTags, setAllTags] = useState([]); const [expandedId, setExpandedId] = useState(null); const [tagsById, setTagsById] = useState({}); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [loading, setLoading] = useState(true); const [taggingId, setTaggingId] = useState(null);
  useEffect(() => { Promise.all([getAllBrowserHistory(), getAllTags()]).then(([records, tags]) => { setHistory(Array.isArray(records) ? records : []); setAllTags(Array.isArray(tags) ? tags : []); }).catch((err) => toast.error(err.response?.data?.error || err.message || 'Unable to load browser history.')).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => { const term = search.trim().toLowerCase(); if (!term) return history; return history.filter((item) => [item.title, item.url, item.domain].some((v) => String(v || '').toLowerCase().includes(term))); }, [history, search]);
  const normalizedSize = pageSize === 'ALL' ? Math.max(filtered.length, 1) : pageSize; const pageCount = Math.max(1, Math.ceil(filtered.length / normalizedSize)); const currentPage = Math.min(page, pageCount); const rows = filtered.slice((currentPage - 1) * normalizedSize, currentPage * normalizedSize);
  const toggleExpand = async (id) => { if (expandedId === id) return setExpandedId(null); setExpandedId(id); if (!tagsById[id]) { try { const tags = await getTagsForHistory(id); setTagsById((prev) => ({ ...prev, [id]: Array.isArray(tags) ? tags : [] })); } catch (err) { toast.error(err.response?.data?.error || err.message || 'Unable to load tags.'); } } };
  const handleManualTag = async (historyId, tagId) => { if (!tagId) return; setTaggingId(historyId); try { const created = await addManualTag(historyId, Number(tagId)); setTagsById((prev) => ({ ...prev, [historyId]: [...(prev[historyId] || []).filter((x) => x.browser_history_tag_Id !== created.browser_history_tag_Id), created] })); toast.success('Tag added to browser history record.'); } catch (err) { toast.error(err.response?.data?.error || err.message || 'Unable to add tag.'); } finally { setTaggingId(null); } };
  const handleRemoveTag = async (historyId, linkId) => { try { await removeTagLink(linkId); setTagsById((prev) => ({ ...prev, [historyId]: (prev[historyId] || []).filter((x) => x.browser_history_tag_Id !== linkId) })); toast.success('Tag link removed.'); } catch (err) { toast.error(err.response?.data?.error || err.message || 'Unable to remove tag link.'); } };
  return <div className="app-page app-page-wide">
    <div className="page-heading d-flex flex-wrap justify-content-between gap-3 mb-4"><div><div className="eyebrow">SYNCED RECORDS</div><h1 className="h3 mb-1">Browser History</h1><p className="text-muted mb-0">Search, inspect and manually correct tags on synchronized Chrome history.</p></div><div className="small text-muted align-self-end">{filtered.length} matching records</div></div>
    <div className="card dashboard-card mb-4"><div className="card-body"><div className="row g-3 align-items-center"><div className="col-lg-8"><input className="form-control" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Search title, URL or domain..." /></div><div className="col-lg-4 text-lg-end small text-muted">Page {currentPage} of {pageCount}</div></div></div></div>
    <div className="card dashboard-card"><div className="card-header">Browser history records</div><div className="card-body p-0"><div className="table-responsive"><table className="table table-hover align-middle mb-0 browser-history-table"><thead><tr><th>Title</th><th>Domain</th><th>Visits</th><th>Last visited</th><th>Tags</th></tr></thead><tbody>
      {!rows.length && <tr><td colSpan={5} className="text-muted p-4">{loading ? 'Loading history…' : 'No matching browser history records.'}</td></tr>}
      {rows.map((h) => { const recordTags = tagsById[h.browser_history_Id] || []; return <Fragment key={h.browser_history_Id}><tr><td style={{ minWidth: 280, maxWidth: 460 }} className="text-truncate"><a href={h.url} target="_blank" rel="noreferrer">{h.title || h.url}</a></td><td>{h.domain || 'unknown'}</td><td>{h.visitCount ?? 0}</td><td>{formatDateTime(h.visitedAt)}</td><td><button className="btn btn-sm btn-outline-secondary" onClick={() => toggleExpand(h.browser_history_Id)}>{expandedId === h.browser_history_Id ? 'Hide tags' : `Show tags${recordTags.length ? ` (${recordTags.length})` : ''}`}</button></td></tr>{expandedId === h.browser_history_Id && <tr><td colSpan={5} className="bg-light-subtle"><div className="d-flex flex-wrap align-items-center gap-2 mb-2">{recordTags.length ? recordTags.map((tag) => <span key={tag.browser_history_tag_Id} className="badge text-bg-secondary d-inline-flex align-items-center gap-1">{tag.tag?.tag_Name || 'Tag'}<button type="button" className="btn btn-sm p-0 text-white tag-remove" onClick={() => handleRemoveTag(h.browser_history_Id, tag.browser_history_tag_Id)} aria-label="Remove tag">×</button></span>) : <span className="text-muted">No tags matched this page.</span>}</div><select className="form-select form-select-sm history-tag-select" value="" disabled={taggingId === h.browser_history_Id} onChange={(e) => handleManualTag(h.browser_history_Id, e.target.value)}><option value="">Add manual tag…</option>{allTags.map((tag) => <option key={tag.tag_Id} value={tag.tag_Id}>{tag.tag_Name}</option>)}</select></td></tr>}</Fragment>; })}
    </tbody></table></div><TablePagination page={currentPage} pageSize={pageSize} total={filtered.length} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} /></div></div>
  </div>;
}
